=== Eretisuii/LND_2023-2024/1ASIRB - Harry Kokal Kokal/AE2.1-Alumnos-1ASIRB-HarryKokalKokal.dtd
<!ELEMENT alumnos (alumno*)>
<!ELEMENT alumno (nombre, apellidos,direccion,telefonos,equipo_deportivo?,aficion*,origen,comentario*,notas,altura?,ayudados?)>
<!ELEMENT direccion (calle,ciudad)>
<!ELEMENT calle EMPTY>
<!ATTLIST calle tipo CDATA #REQUIRED>
<!ATTLIST calle nombre CDATA #REQUIRED>
<!ATTLIST calle numero CDATA #REQUIRED>
<!ELEMENT telefonos (telefono_alumno, ((telefono_madre,telefono_padre) | telefono_tutor))>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT equipo_deportivo (#PCDATA)>
<!ELEMENT aficion (#PCDATA)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT telefono_alumno (#PCDATA)>
<!ELEMENT telefono_madre (#PCDATA)>
<!ELEMENT telefono_padre (#PCDATA)>
<!ELEMENT telefono_tutor (#PCDATA)>
<!ELEMENT origen EMPTY>
<!ATTLIST origen nacimiento (extranjero | español) "español" >
<!ELEMENT comentario (#PCDATA)>
<!ELEMENT notas ((evalucion | texto), nota)>
<!ELEMENT evalucion (#PCDATA)>
<!ELEMENT nota (#PCDATA)>
<!ELEMENT texto (#PCDATA)>
<!ATTLIST alumno id ID #REQUIRED>
<!ELEMENT altura EMPTY>
<!ATTLIST altura cm CDATA #REQUIRED>
<!ATTLIST alumno sexo (hombre | mujer | ns) "ns">
<!ELEMENT ayudados EMPTY>
<!ATTLIST ayudados por IDREFS #REQUIRED>

=== Eretisuii/LND_2023-2024/UT2/Entregable/1ASIRB - Harry Kokal Kokal/AE2.1-Alumnos-1ASIRB-HarryKokalKokal.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE alumnos SYSTEM "AE2.1-Alumnos-1ASIRB-HarryKokalKokal.dtd">

<alumnos>
  <alumno id="HKK" sexo="hombre">
    <nombre>Harry</nombre>
    <apellidos>Kokal Kokal</apellidos>
    <direccion>
      <calle tipo="calle" nombre="Bill Evans" numero="4"/>
      <ciudad>Badajoz</ciudad>
    </direccion>
    <telefonos>
      <telefono_alumno>789456123</telefono_alumno>
      <telefono_madre>987654321</telefono_madre>
      <telefono_padre>741852963</telefono_padre>
    </telefonos>
    <equipo_deportivo>Fútbol Club Barcelona</equipo_deportivo>
    <aficion>jugar al fc24</aficion>
    <aficion>estudiar 24h xml</aficion>
    <origen/>
    <comentario>Chico aplicado</comentario>
    <notas>
      <evalucion>primera</evalucion>
      <nota>10</nota>
    </notas>
    <altura cm="170"/>
  </alumno>
  <alumno id="LGD" sexo="hombre">
  <nombre>Luis</nombre>
  <apellidos>Gómez Díaz</apellidos>
  <direccion>
    <calle tipo="avenida" nombre="Bill Evans" numero="4"/>
    <ciudad>Santa cruz</ciudad>
  </direccion>
  <telefonos>
    <telefono_alumno>987465464</telefono_alumno>
    <telefono_madre>354867484</telefono_madre>
    <telefono_padre>945984664</telefono_padre>
  </telefonos>
  <origen nacimiento="extranjero"/>
  <notas>
    <evalucion>segunda</evalucion>
    <nota>1</nota>
  </notas>
  <altura cm="189"/>
  <ayudados por="HKK"/>
  </alumno>
  <alumno id="JFB" sexo="hombre">
  <nombre>Juan</nombre>
  <apellidos>Frances Blanco</apellidos>
  <direccion>
    <calle tipo="calle" nombre="Jesus y Melo" numero="4"/>
    <ciudad>Santa cruz</ciudad>
  </direccion>
  <telefonos>
    <telefono_alumno>987465464</telefono_alumno>
    <telefono_madre>354867484</telefono_madre>
    <telefono_padre>945984664</telefono_padre>
  </telefonos>
  <origen/>
  <notas>
    <evalucion>primera</evalucion>
    <nota>9</nota>
  </notas>
  <altura cm="179"/>
  <ayudados por="HKK"/>
  </alumno>
  <alumno id="MFB" sexo="hombre">
  <nombre>Marco</nombre>
  <apellidos>Frances Blanco</apellidos>
  <direccion>
    <calle tipo="calle" nombre="Jesus" numero="9"/>
    <ciudad>Santa cruz</ciudad>
  </direccion>
  <telefonos>
    <telefono_alumno>987465464</telefono_alumno>
    <telefono_madre>354867484</telefono_madre>
    <telefono_padre>945984664</telefono_padre>
  </telefonos>
  <origen/>
  <notas>
    <evalucion>primera</evalucion>
    <nota>5</nota>
  </notas>
  <altura cm="174"/>
  <ayudados por="HKK"/>
  </alumno>
  <alumno id="JJL" sexo="mujer">
  <nombre>Juan</nombre>
  <apellidos>Jesus Lorca</apellidos>
  <direccion>
    <calle tipo="calle" nombre="prince de españa" numero="8"/>
    <ciudad>Santa cruz</ciudad>
  </direccion>
  <telefonos>
    <telefono_alumno>987465464</telefono_alumno>
    <telefono_madre>354867484</telefono_madre>
    <telefono_padre>945984664</telefono_padre>
  </telefonos>
  <origen/>
  <notas>
    <evalucion>primera</evalucion>
    <nota>6</nota>
  </notas>
  <altura cm="169"/>
  <ayudados por="HKK"/>
  </alumno>
</alumnos>
