=== Eretisuii/LND_2023-2024/Examen UT1 Y UT2/E2.1_kokal_kokal_harry.dtd
<!ELEMENT supermercados (supermercado)+>
    <!ATTLIST supermercado nombre CDATA #IMPLIED>

<!ELEMENT supermercado (articulos)>
<!ELEMENT articulos (articulo)+>
    <!ATTLIST articulo codigo NMTOKENS #REQUIRED>

<!ELEMENT articulo (nombre,descripcion,marca?,cantidad,seccion,precio,ofertas,perecedero)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT marca (#PCDATA)>

<!ELEMENT cantidad (#PCDATA)>
    <!ATTLIST cantidad medida (litros|gramos|unidades) #REQUIRED>

<!ELEMENT seccion (#PCDATA|sub_seccion)*>
<!ELEMENT sub_seccion (#PCDATA)>

<!ELEMENT precio (#PCDATA)>
    <!ATTLIST precio moneda (euro|dólar) #REQUIRED>

<!ELEMENT ofertas (oferta)*>
<!ELEMENT oferta (#PCDATA)>
    <!ATTLIST oferta comienzo CDATA #REQUIRED>
    <!ATTLIST oferta final CDATA #REQUIRED>

<!ELEMENT perecedero (fecha_fabricación,fecha_caducidad)>
<!ELEMENT fecha_fabricación (#PCDATA)>
<!ELEMENT fecha_caducidad (#PCDATA)>

=== Eretisuii/LND_2023-2024/Examen UT1 Y UT2/E2.1_kokal_kokal_harry.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE supermercados SYSTEM "E2.1_kokal_kokal_harry.dtd">
<supermercados>
    <supermercado>
        <articulos>
            <articulo codigo="1">
                <nombre>Leche</nombre>
                <descripcion>freca</descripcion>
                <marca>Puleva</marca>
                <cantidad medida="litros">1.5</cantidad>
                <seccion>lacteo</seccion>
                <precio moneda="euro">1</precio>
                <ofertas>
                    <oferta comienzo="22/06/2002" final="10/25/2555">hola</oferta>
                </ofertas>
                <perecedero>
                    <fecha_fabricación></fecha_fabricación>
                    <fecha_caducidad></fecha_caducidad>
                </perecedero>
            </articulo>
            <articulo codigo="2">
                <nombre>Leche</nombre>
                <descripcion>natural</descripcion>
                <cantidad medida="gramos">1.5</cantidad>
                <seccion>
                    <sub_seccion>lacteo</sub_seccion>
                </seccion>
                <precio moneda="dólar">1</precio>
                <ofertas>
                    <oferta comienzo="22/06/2002" final="10/25/2555">hola</oferta>
                </ofertas>
                <perecedero>
                    <fecha_fabricación></fecha_fabricación>
                    <fecha_caducidad></fecha_caducidad>
                </perecedero>
            </articulo>
            <articulo codigo="3">
                <nombre>Leche</nombre>
                <descripcion>natural</descripcion>
                <cantidad medida="unidades">1</cantidad>
                <seccion>lacteo
                    <sub_seccion>lacteo</sub_seccion>
                </seccion>
                <precio moneda="dólar">1</precio>
                <ofertas>
                    <oferta comienzo="22/06/2002" final="10/25/2555">hola</oferta>
                </ofertas>
                <perecedero>
                    <fecha_fabricación></fecha_fabricación>
                    <fecha_caducidad></fecha_caducidad>
                </perecedero>
            </articulo>
        </articulos>
    </supermercado>
</supermercados>
